services:
  - type: web
    name: terabox-telegram-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/healthz
    envVars:
      - key: TERABOX_COOKIE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: SESSION_SECRET
        sync: false
